version: '2'
services:
  snmptrap:
    image: fatalglitch/rpi-snmp
    container_name: rpi-snmp
    ports:
      - "162:162/udp"
    restart: always
    volumes:
      - ./conf:/etc/snmp
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    container_name: logstash
    ports:
      - 4567:4567
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
      - ./logstash/since-db/:/var/lib/logstash/
    environment:
      NODE_NAME: rpi-snmptrap
